### ISSUE TITLE
0.3.0: won't compile with Qt 5.8.0

### ISSUE THREAD

**Issue by ferdna** [fpoussin/QtUsb#7]
```
g++ -c -m64 -pipe -O2 -fPIC -O2 -Wall -W -D_REENTRANT -fPIC -DQUSB_LIBRARY -DQLIBUSB -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt/mkspecs/linux-g++-64 -I. -I/usr/lib64/qt/include/QtCore -I/usr/lib64/qt/include -I. -Ishared -o shared/qbaseusb.o qbaseusb.cpp
g++ -c -m64 -pipe -O2 -fPIC -O2 -Wall -W -D_REENTRANT -fPIC -DQUSB_LIBRARY -DQLIBUSB -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt/mkspecs/linux-g++-64 -I. -I/usr/lib64/qt/include/QtCore -I/usr/lib64/qt/include -I. -Ishared -o shared/qusbmanager.o qusbmanager.cpp
In file included from qusbmanager.cpp:1:0:
qusbmanager.h: In function ‘int hotplugCallback(libusb_context*, libusb_device*, libusb_hotplug_event, void*)’:
qusbmanager.h:49:8: error: ‘void QUsbManager::deviceInserted(QtUsb::FilterList)’ is protected
   void deviceInserted(QtUsb::FilterList filters);
        ^
qusbmanager.cpp:28:45: error: within this context
     emit manager->deviceInserted(device_list);
                                             ^
In file included from qusbmanager.cpp:1:0:
qusbmanager.h:55:8: error: ‘void QUsbManager::deviceRemoved(QtUsb::FilterList)’ is protected
   void deviceRemoved(QtUsb::FilterList filters);
        ^
qusbmanager.cpp:36:46: error: within this context
       emit manager->deviceRemoved(device_list);
                                              ^
Makefile.Shared:224: recipe for target 'shared/qusbmanager.o' failed
make[2]: *** [shared/qusbmanager.o] Error 1
```

**Comment by ferdna** [comment]
never mind. I was using qmake 4 instead of qmake 5. my bad. you can delete. thank you.
